spring:
  datasource:
    username: ${MYSQL_USERNAME:}
    password: ${MYSQL_PASSWORD:}
    url: ${MYSQL_URL:}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maxLifetime: 600000  # 约 10 分钟
      idleTimeout: 600000  # 10 分钟
      ConnectionTestQuery: SELECT 1  # 用于验证连接有效性
  data:
    redis:
      #数据库索引
      database: 0
      host: ${REDIS_HOST:}
      port: ${REDIS_PORT:}
      password: ${REDIS_PASSWORD:}
      #连接超时时间（ms）
      timeout: 5000
      # 自定义redis默认过期时间（单位：时）
      expire-time: 24
server:
  port: 18800
  servlet:
    context-path: /fish-api
  tomcat:
    max-swallow-size: -1

#mybatis:
#  mapper-locations: classpath:com/pond/build/mapper/*.xml
#  type-aliases-package: com.pond.build.model
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  # 搜索指定包别名
  type-aliases-package: com.pond.build.model
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:com/pond/build/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# https://blog.csdn.net/HLXTU/article/details/130770881
minio:
  endpoint: ${MINIO_ENDPOINT:}
  accessKey: ${MINIO_ACCESSKEY:}
  secretKey: ${MINIO_SECRETKEY:}
#  bucketName: fishtest

logging:
  config: classpath:Log4j2-spring.xml

pond:
  name: fish
  prefix: Bearer

oauth2:
  github:
    clientId:
    clientSecret:
    redirectUri: