spring:
  datasource:
    username: root
    password: root
#    allowMultiQueries=true  支持批处理
    url: jdbc:mysql://localhost:3306/fishdb?allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8999

redis:
  #数据库索引
  database: 0
  host: 127.0.0.1
  port: 6379
  password:
  #连接超时时间（ms）
  timeout: 5000
  # 自定义redis默认过期时间（单位：时）
  expire-time: 24
  jedis:
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: -1
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1

mybatis:
  mapper-locations: classpath:com/pond/build/mapper/*.xml
  type-aliases-package: com.pond.build.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:Log4j2-spring.xml


pond:
  name: fish
