spring:
  datasource:
    username: root
    password: root
#    password: 71789
#    allowMultiQueries=true  支持批处理
    url: jdbc:mysql://localhost:3306/fishdb?allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8999
  servlet:
    context-path: /fish-api

redis:
  #数据库索引
  database: 0
  host: 127.0.0.1
  port: 6379
  password:
  #连接超时时间（ms）
  timeout: 5000
  # 自定义redis默认过期时间（单位：时）
  expire-time: 24

#mybatis:
#  mapper-locations: classpath:com/pond/build/mapper/*.xml
#  type-aliases-package: com.pond.build.model
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  # 搜索指定包别名
  type-aliases-package: com.pond.build.model
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:com/pond/build/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# https://blog.csdn.net/HLXTU/article/details/130770881
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: myname
  secretKey: mypassword
#  bucketName: fishtest

logging:
  config: classpath:Log4j2-spring.xml


pond:
  name: fish
  prefix: Bearer
